/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.utfpr.pb.view;

import br.com.utfpr.pb.controller.UsuarioController;
import br.com.utfpr.pb.enumeration.Menu;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 * @author João
 */
public class PrincipalView extends javax.swing.JFrame {

    private UsuarioController usuarioController = UsuarioController.getInstance();

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        addMenus();

        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);

        //login();
    }

    private void login() {
        LoginView loginView = new LoginView(null, true);
        loginView.setVisible(true);

        labelUsuario.setText("Olá " + usuarioController.getUsuarioLogado().getNome());
    }

    private void addMenus() {
        for (Menu menu : Menu.values()) {
            Icon icon = new ImageIcon(getClass().getResource("/icon/" + menu.getIcon()));

            AbstractAction action = new AbstractAction(menu.getDescricao(), icon) {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        Class.forName("br.com.utfpr.pb.view." + menu.getClazz()).newInstance();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            };

            if (menu.getTask().equals("cadastros")) {
                taskPaneCadastros.add(action);
            } else if (menu.getTask().equals("pedidos")) {
                taskPanePedidos.add(action);
            } else if (menu.getTask().equals("financeiro")) {
                taskPaneFinanceiro.add(action);
            } else {
                taskPaneRelatorios.add(action);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        labelUsuario = new javax.swing.JLabel();
        taskPaneCadastros = new org.jdesktop.swingx.JXTaskPane();
        taskPanePedidos = new org.jdesktop.swingx.JXTaskPane();
        taskPaneFinanceiro = new org.jdesktop.swingx.JXTaskPane();
        taskPaneRelatorios = new org.jdesktop.swingx.JXTaskPane();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jXTaskPaneContainer1.setLayout(verticalLayout1);

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXTaskPaneContainer1.add(labelUsuario);

        taskPaneCadastros.setTitle("Cadastros");
        jXTaskPaneContainer1.add(taskPaneCadastros);

        taskPanePedidos.setTitle("Pedidos");
        jXTaskPaneContainer1.add(taskPanePedidos);

        taskPaneFinanceiro.setTitle("Financeiro");
        jXTaskPaneContainer1.add(taskPaneFinanceiro);

        taskPaneRelatorios.setTitle("Relatórios");
        jXTaskPaneContainer1.add(taskPaneRelatorios);

        jDesktopPane.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuSair.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItem1);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuSair;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private javax.swing.JLabel labelUsuario;
    private org.jdesktop.swingx.JXTaskPane taskPaneCadastros;
    private org.jdesktop.swingx.JXTaskPane taskPaneFinanceiro;
    private org.jdesktop.swingx.JXTaskPane taskPanePedidos;
    private org.jdesktop.swingx.JXTaskPane taskPaneRelatorios;
    // End of variables declaration//GEN-END:variables
}
